/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_authentification (void)
{
  GtkWidget *authentification;
  GtkWidget *fixed1;
  GtkWidget *entryid;
  GtkWidget *entrymdp;
  GtkWidget *entryr;
  GtkWidget *image23;
  GtkWidget *image29;
  GtkWidget *label1;
  GtkWidget *label2;
  GtkWidget *label3;
  GtkWidget *buttonc;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label4;

  authentification = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (authentification), _("authentification"));

  fixed1 = gtk_fixed_new ();
  gtk_widget_show (fixed1);
  gtk_container_add (GTK_CONTAINER (authentification), fixed1);

  entryid = gtk_entry_new ();
  gtk_widget_show (entryid);
  gtk_fixed_put (GTK_FIXED (fixed1), entryid, 136, 120);
  gtk_widget_set_size_request (entryid, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryid), 8226);

  entrymdp = gtk_entry_new ();
  gtk_widget_show (entrymdp);
  gtk_fixed_put (GTK_FIXED (fixed1), entrymdp, 136, 168);
  gtk_widget_set_size_request (entrymdp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrymdp), 8226);

  entryr = gtk_entry_new ();
  gtk_widget_show (entryr);
  gtk_fixed_put (GTK_FIXED (fixed1), entryr, 136, 216);
  gtk_widget_set_size_request (entryr, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryr), 8226);

  image23 = create_pixmap (authentification, "bienvenue-300x210.jpg");
  gtk_widget_show (image23);
  gtk_fixed_put (GTK_FIXED (fixed1), image23, 32, 8);
  gtk_widget_set_size_request (image23, 280, 104);

  image29 = create_pixmap (authentification, "index.jpeg");
  gtk_widget_show (image29);
  gtk_fixed_put (GTK_FIXED (fixed1), image29, 8, 80);
  gtk_widget_set_size_request (image29, 320, 256);

  label1 = gtk_label_new (_("           Identifiant :"));
  gtk_widget_show (label1);
  gtk_fixed_put (GTK_FIXED (fixed1), label1, 0, 120);
  gtk_widget_set_size_request (label1, 128, 33);

  label2 = gtk_label_new (_("       Mot de passe :"));
  gtk_widget_show (label2);
  gtk_fixed_put (GTK_FIXED (fixed1), label2, 0, 168);
  gtk_widget_set_size_request (label2, 136, 33);

  label3 = gtk_label_new (_("         Role :"));
  gtk_widget_show (label3);
  gtk_fixed_put (GTK_FIXED (fixed1), label3, 0, 216);
  gtk_widget_set_size_request (label3, 128, 33);

  buttonc = gtk_button_new ();
  gtk_widget_show (buttonc);
  gtk_fixed_put (GTK_FIXED (fixed1), buttonc, 160, 248);
  gtk_widget_set_size_request (buttonc, 112, 32);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (buttonc), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-dialog-authentication", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label4 = gtk_label_new_with_mnemonic (_("Connexion"));
  gtk_widget_show (label4);
  gtk_box_pack_start (GTK_BOX (hbox1), label4, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonc, "clicked",
                    G_CALLBACK (on_buttonc_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (authentification, authentification, "authentification");
  GLADE_HOOKUP_OBJECT (authentification, fixed1, "fixed1");
  GLADE_HOOKUP_OBJECT (authentification, entryid, "entryid");
  GLADE_HOOKUP_OBJECT (authentification, entrymdp, "entrymdp");
  GLADE_HOOKUP_OBJECT (authentification, entryr, "entryr");
  GLADE_HOOKUP_OBJECT (authentification, image23, "image23");
  GLADE_HOOKUP_OBJECT (authentification, image29, "image29");
  GLADE_HOOKUP_OBJECT (authentification, label1, "label1");
  GLADE_HOOKUP_OBJECT (authentification, label2, "label2");
  GLADE_HOOKUP_OBJECT (authentification, label3, "label3");
  GLADE_HOOKUP_OBJECT (authentification, buttonc, "buttonc");
  GLADE_HOOKUP_OBJECT (authentification, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (authentification, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (authentification, image1, "image1");
  GLADE_HOOKUP_OBJECT (authentification, label4, "label4");

  return authentification;
}

GtkWidget*
create_administrateur (void)
{
  GtkWidget *administrateur;
  GtkWidget *fixed2;
  GtkWidget *image30;
  GtkWidget *buttonretoutadib12;
  GtkWidget *alignment23;
  GtkWidget *hbox23;
  GtkWidget *image39;
  GtkWidget *label69;
  GtkWidget *buttontb;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label7;
  GtkWidget *buttonu;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label6;

  administrateur = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (administrateur), _("administrateur"));

  fixed2 = gtk_fixed_new ();
  gtk_widget_show (fixed2);
  gtk_container_add (GTK_CONTAINER (administrateur), fixed2);

  image30 = create_pixmap (administrateur, "99946F345ACEE21A25.jpeg");
  gtk_widget_show (image30);
  gtk_fixed_put (GTK_FIXED (fixed2), image30, 0, 0);
  gtk_widget_set_size_request (image30, 448, 472);

  buttonretoutadib12 = gtk_button_new ();
  gtk_widget_show (buttonretoutadib12);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonretoutadib12, 176, 408);
  gtk_widget_set_size_request (buttonretoutadib12, 106, 32);

  alignment23 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment23);
  gtk_container_add (GTK_CONTAINER (buttonretoutadib12), alignment23);

  hbox23 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox23);
  gtk_container_add (GTK_CONTAINER (alignment23), hbox23);

  image39 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image39);
  gtk_box_pack_start (GTK_BOX (hbox23), image39, FALSE, FALSE, 0);

  label69 = gtk_label_new_with_mnemonic (_("button1"));
  gtk_widget_show (label69);
  gtk_box_pack_start (GTK_BOX (hbox23), label69, FALSE, FALSE, 0);

  buttontb = gtk_button_new ();
  gtk_widget_show (buttontb);
  gtk_fixed_put (GTK_FIXED (fixed2), buttontb, 240, 336);
  gtk_widget_set_size_request (buttontb, 184, 56);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (buttontb), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label7 = gtk_label_new_with_mnemonic (_("Tableau de bord :"));
  gtk_widget_show (label7);
  gtk_box_pack_start (GTK_BOX (hbox3), label7, FALSE, FALSE, 0);

  buttonu = gtk_button_new ();
  gtk_widget_show (buttonu);
  gtk_fixed_put (GTK_FIXED (fixed2), buttonu, 32, 336);
  gtk_widget_set_size_request (buttonu, 200, 56);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (buttonu), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label6 = gtk_label_new_with_mnemonic (_("Gestion d'utilusateurs"));
  gtk_widget_show (label6);
  gtk_box_pack_start (GTK_BOX (hbox2), label6, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonretoutadib12, "clicked",
                    G_CALLBACK (on_buttonretoutadib12_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttontb, "clicked",
                    G_CALLBACK (on_buttontb_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonu, "clicked",
                    G_CALLBACK (on_buttonu_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (administrateur, administrateur, "administrateur");
  GLADE_HOOKUP_OBJECT (administrateur, fixed2, "fixed2");
  GLADE_HOOKUP_OBJECT (administrateur, image30, "image30");
  GLADE_HOOKUP_OBJECT (administrateur, buttonretoutadib12, "buttonretoutadib12");
  GLADE_HOOKUP_OBJECT (administrateur, alignment23, "alignment23");
  GLADE_HOOKUP_OBJECT (administrateur, hbox23, "hbox23");
  GLADE_HOOKUP_OBJECT (administrateur, image39, "image39");
  GLADE_HOOKUP_OBJECT (administrateur, label69, "label69");
  GLADE_HOOKUP_OBJECT (administrateur, buttontb, "buttontb");
  GLADE_HOOKUP_OBJECT (administrateur, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (administrateur, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (administrateur, image3, "image3");
  GLADE_HOOKUP_OBJECT (administrateur, label7, "label7");
  GLADE_HOOKUP_OBJECT (administrateur, buttonu, "buttonu");
  GLADE_HOOKUP_OBJECT (administrateur, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (administrateur, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (administrateur, image2, "image2");
  GLADE_HOOKUP_OBJECT (administrateur, label6, "label6");

  return administrateur;
}

GtkWidget*
create_Tableu_de_bord_ (void)
{
  GtkWidget *Tableu_de_bord_;
  GtkWidget *fixed3;
  GtkWidget *image31;
  GtkWidget *buttonibret;
  GtkWidget *alignment22;
  GtkWidget *hbox22;
  GtkWidget *image36;
  GtkWidget *label67;
  GtkWidget *buttongt;
  GtkWidget *alignment8;
  GtkWidget *hbox8;
  GtkWidget *image8;
  GtkWidget *label12;
  GtkWidget *buttongca;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *label11;
  GtkWidget *buttongo;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label9;
  GtkWidget *buttonge;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label8;
  GtkWidget *buttongc;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label10;
  GtkWidget *buttongcl;
  GtkWidget *alignment9;
  GtkWidget *hbox9;
  GtkWidget *image9;
  GtkWidget *label13;

  Tableu_de_bord_ = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Tableu_de_bord_), _("Tableau de bord "));

  fixed3 = gtk_fixed_new ();
  gtk_widget_show (fixed3);
  gtk_container_add (GTK_CONTAINER (Tableu_de_bord_), fixed3);

  image31 = create_pixmap (Tableu_de_bord_, "timo.jpg");
  gtk_widget_show (image31);
  gtk_fixed_put (GTK_FIXED (fixed3), image31, -8, 0);
  gtk_widget_set_size_request (image31, 648, 448);

  buttonibret = gtk_button_new ();
  gtk_widget_show (buttonibret);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonibret, 256, 392);
  gtk_widget_set_size_request (buttonibret, 114, 29);

  alignment22 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment22);
  gtk_container_add (GTK_CONTAINER (buttonibret), alignment22);

  hbox22 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox22);
  gtk_container_add (GTK_CONTAINER (alignment22), hbox22);

  image36 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image36);
  gtk_box_pack_start (GTK_BOX (hbox22), image36, FALSE, FALSE, 0);

  label67 = gtk_label_new_with_mnemonic (_("RETOUR"));
  gtk_widget_show (label67);
  gtk_box_pack_start (GTK_BOX (hbox22), label67, FALSE, FALSE, 0);

  buttongt = gtk_button_new ();
  gtk_widget_show (buttongt);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongt, 336, 280);
  gtk_widget_set_size_request (buttongt, 280, 80);

  alignment8 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment8);
  gtk_container_add (GTK_CONTAINER (buttongt), alignment8);

  hbox8 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox8);
  gtk_container_add (GTK_CONTAINER (alignment8), hbox8);

  image8 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image8);
  gtk_box_pack_start (GTK_BOX (hbox8), image8, FALSE, FALSE, 0);

  label12 = gtk_label_new_with_mnemonic (_("Gestion de troupeaux :"));
  gtk_widget_show (label12);
  gtk_box_pack_start (GTK_BOX (hbox8), label12, FALSE, FALSE, 0);

  buttongca = gtk_button_new ();
  gtk_widget_show (buttongca);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongca, 336, 176);
  gtk_widget_set_size_request (buttongca, 280, 72);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttongca), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  label11 = gtk_label_new_with_mnemonic (_("Gestion de calendrier :"));
  gtk_widget_show (label11);
  gtk_box_pack_start (GTK_BOX (hbox7), label11, FALSE, FALSE, 0);

  buttongo = gtk_button_new ();
  gtk_widget_show (buttongo);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongo, 328, 72);
  gtk_widget_set_size_request (buttongo, 288, 72);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (buttongo), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label9 = gtk_label_new_with_mnemonic (_("Gestion des ouvriers :"));
  gtk_widget_show (label9);
  gtk_box_pack_start (GTK_BOX (hbox5), label9, FALSE, FALSE, 0);

  buttonge = gtk_button_new ();
  gtk_widget_show (buttonge);
  gtk_fixed_put (GTK_FIXED (fixed3), buttonge, 24, 72);
  gtk_widget_set_size_request (buttonge, 272, 72);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (buttonge), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label8 = gtk_label_new_with_mnemonic (_("Gestion des equipement :"));
  gtk_widget_show (label8);
  gtk_box_pack_start (GTK_BOX (hbox4), label8, FALSE, FALSE, 0);

  buttongc = gtk_button_new ();
  gtk_widget_show (buttongc);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongc, 24, 176);
  gtk_widget_set_size_request (buttongc, 272, 72);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (buttongc), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label10 = gtk_label_new_with_mnemonic (_("Gestion des capteurs :"));
  gtk_widget_show (label10);
  gtk_box_pack_start (GTK_BOX (hbox6), label10, FALSE, FALSE, 0);

  buttongcl = gtk_button_new ();
  gtk_widget_show (buttongcl);
  gtk_fixed_put (GTK_FIXED (fixed3), buttongcl, 24, 280);
  gtk_widget_set_size_request (buttongcl, 272, 80);

  alignment9 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment9);
  gtk_container_add (GTK_CONTAINER (buttongcl), alignment9);

  hbox9 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox9);
  gtk_container_add (GTK_CONTAINER (alignment9), hbox9);

  image9 = gtk_image_new_from_stock ("gtk-execute", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image9);
  gtk_box_pack_start (GTK_BOX (hbox9), image9, FALSE, FALSE, 0);

  label13 = gtk_label_new_with_mnemonic (_("Gestion de clients :"));
  gtk_widget_show (label13);
  gtk_box_pack_start (GTK_BOX (hbox9), label13, FALSE, FALSE, 0);

  g_signal_connect ((gpointer) buttonibret, "clicked",
                    G_CALLBACK (on_buttonibret_enter),
                    NULL);
  g_signal_connect ((gpointer) buttongt, "clicked",
                    G_CALLBACK (on_buttongt_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongca, "clicked",
                    G_CALLBACK (on_buttongca_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongo, "clicked",
                    G_CALLBACK (on_buttongo_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonge, "clicked",
                    G_CALLBACK (on_buttonge_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongc, "clicked",
                    G_CALLBACK (on_buttongc_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttongcl, "clicked",
                    G_CALLBACK (on_buttongcl_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Tableu_de_bord_, Tableu_de_bord_, "Tableu_de_bord_");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, fixed3, "fixed3");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image31, "image31");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, buttonibret, "buttonibret");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, alignment22, "alignment22");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, hbox22, "hbox22");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image36, "image36");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, label67, "label67");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, buttongt, "buttongt");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, alignment8, "alignment8");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, hbox8, "hbox8");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image8, "image8");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, label12, "label12");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, buttongca, "buttongca");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image7, "image7");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, label11, "label11");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, buttongo, "buttongo");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image5, "image5");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, label9, "label9");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, buttonge, "buttonge");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image4, "image4");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, label8, "label8");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, buttongc, "buttongc");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image6, "image6");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, label10, "label10");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, buttongcl, "buttongcl");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, alignment9, "alignment9");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, hbox9, "hbox9");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, image9, "image9");
  GLADE_HOOKUP_OBJECT (Tableu_de_bord_, label13, "label13");

  return Tableu_de_bord_;
}

GtkWidget*
create_Gestion_d_ouvriers (void)
{
  GtkWidget *Gestion_d_ouvriers;
  GtkWidget *Gestion_d_ouvrier_;
  GtkWidget *image41;
  GtkWidget *label19;
  GtkWidget *notebook1;
  GtkWidget *fixed5;
  GtkWidget *entrynomi;
  GtkWidget *entryprenomi;
  GtkWidget *entryidentifianti;
  GtkWidget *entryspecialitei;
  GtkWidget *entrynumrodetelephonei;
  GtkWidget *buttonre;
  GtkWidget *alignment19;
  GtkWidget *hbox19;
  GtkWidget *image27;
  GtkWidget *label58;
  GtkWidget *buttonajouti;
  GtkWidget *alignment10;
  GtkWidget *hbox10;
  GtkWidget *image11;
  GtkWidget *label26;
  GtkWidget *image10;
  GtkWidget *label22;
  GtkWidget *label21;
  GtkWidget *label20;
  GtkWidget *label23;
  GtkWidget *labelspecaj;
  GtkWidget *label24;
  GtkWidget *label25;
  GtkWidget *labelnomaj;
  GtkWidget *labelprenomaj;
  GtkWidget *labelidentaj;
  GtkWidget *labeltelaj;
  GtkWidget *label14;
  GtkWidget *fixed10;
  GtkWidget *entryidentifianti1;
  GtkWidget *entrynomi1;
  GtkWidget *entryprenomi1;
  GtkWidget *entryspecialitei1;
  GtkWidget *entrynumdeteli1;
  GtkWidget *infoi;
  GtkWidget *entryidentifiantimodi;
  GtkWidget *buttonmodifieri;
  GtkWidget *alignment15;
  GtkWidget *hbox15;
  GtkWidget *image17;
  GtkWidget *label45;
  GtkWidget *buttoninfoi;
  GtkWidget *alignment14;
  GtkWidget *hbox14;
  GtkWidget *image16;
  GtkWidget *label44;
  GtkWidget *labelCheckNomModif;
  GtkWidget *labelCheckPreomModif;
  GtkWidget *labelCheckidModif;
  GtkWidget *labelCheckspModif;
  GtkWidget *labelCheckTelModif;
  GtkWidget *label39;
  GtkWidget *checkbuttonmodifieri;
  GtkWidget *label43;
  GtkWidget *label42;
  GtkWidget *label56;
  GtkWidget *label41;
  GtkWidget *label40;
  GtkWidget *labelCheckidModif2;
  GtkWidget *label15;
  GtkWidget *fixed7;
  GtkWidget *treeview1;
  GtkWidget *entryidsupp;
  GtkWidget *buttonsupprimeri;
  GtkWidget *alignment11;
  GtkWidget *hbox11;
  GtkWidget *image13;
  GtkWidget *label33;
  GtkWidget *label55;
  GtkWidget *image12;
  GtkWidget *image37;
  GtkWidget *image38;
  GtkWidget *label68;
  GtkWidget *label32;
  GtkWidget *buttonaffichsupp;
  GtkWidget *alignment17;
  GtkWidget *hbox17;
  GtkWidget *image25;
  GtkWidget *label54;
  GtkWidget *label16;
  GtkWidget *fixed8;
  GtkWidget *entryidentifianti2;
  GtkWidget *infoi2;
  GtkWidget *treeview2;
  GtkWidget *buttonchercheri;
  GtkWidget *alignment13;
  GtkWidget *hbox13;
  GtkWidget *image15;
  GtkWidget *label37;
  GtkWidget *image20;
  GtkWidget *label31;
  GtkWidget *buttonretourchercher;
  GtkWidget *alignment20;
  GtkWidget *hbox20;
  GtkWidget *image28;
  GtkWidget *label64;
  GtkWidget *label53;
  GtkWidget *buttonAffichecherch;
  GtkWidget *alignment18;
  GtkWidget *hbox18;
  GtkWidget *image26;
  GtkWidget *label57;
  GtkWidget *label17;
  GtkWidget *fixed9;
  GtkWidget *entryidentifianti3;
  GtkWidget *treeview3;
  GtkWidget *buttonconfirmeri;
  GtkWidget *alignment16;
  GtkWidget *hbox16;
  GtkWidget *image19;
  GtkWidget *label52;
  GtkWidget *label50;
  GtkWidget *label49;
  GtkWidget *label65;
  GtkWidget *comboboxentryannee3;
  GtkWidget *comboboxentrymois3;
  GtkWidget *comboboxentryjour3;
  GtkWidget *label47;
  GtkWidget *label48;
  GtkWidget *buttonafficherab;
  GtkWidget *alignment21;
  GtkWidget *hbox21;
  GtkWidget *image35;
  GtkWidget *label66;
  GtkWidget *label51;
  GtkWidget *image18;
  GtkWidget *label18;
  GtkWidget *image42;

  Gestion_d_ouvriers = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (Gestion_d_ouvriers), _("Gestion d ouvriers"));

  Gestion_d_ouvrier_ = gtk_fixed_new ();
  gtk_widget_show (Gestion_d_ouvrier_);
  gtk_container_add (GTK_CONTAINER (Gestion_d_ouvriers), Gestion_d_ouvrier_);

  image41 = create_pixmap (Gestion_d_ouvriers, "99946F345ACEE21A25.jpeg");
  gtk_widget_show (image41);
  gtk_fixed_put (GTK_FIXED (Gestion_d_ouvrier_), image41, 0, 0);
  gtk_widget_set_size_request (image41, 640, 208);

  label19 = gtk_label_new (_("<span font_desc='black'foreground='black'> BIENVENU(E) DANS L'OUTIL DE GESTION DES OUVRIERS :</span>"));
  gtk_widget_show (label19);
  gtk_fixed_put (GTK_FIXED (Gestion_d_ouvrier_), label19, 48, 0);
  gtk_widget_set_size_request (label19, 496, 104);
  gtk_label_set_use_markup (GTK_LABEL (label19), TRUE);

  notebook1 = gtk_notebook_new ();
  gtk_widget_show (notebook1);
  gtk_fixed_put (GTK_FIXED (Gestion_d_ouvrier_), notebook1, 0, 88);
  gtk_widget_set_size_request (notebook1, 576, 448);

  fixed5 = gtk_fixed_new ();
  gtk_widget_show (fixed5);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed5);

  entrynomi = gtk_entry_new ();
  gtk_widget_show (entrynomi);
  gtk_fixed_put (GTK_FIXED (fixed5), entrynomi, 192, 88);
  gtk_widget_set_size_request (entrynomi, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomi), 8226);

  entryprenomi = gtk_entry_new ();
  gtk_widget_show (entryprenomi);
  gtk_fixed_put (GTK_FIXED (fixed5), entryprenomi, 192, 144);
  gtk_widget_set_size_request (entryprenomi, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomi), 8226);

  entryidentifianti = gtk_entry_new ();
  gtk_widget_show (entryidentifianti);
  gtk_fixed_put (GTK_FIXED (fixed5), entryidentifianti, 192, 192);
  gtk_widget_set_size_request (entryidentifianti, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidentifianti), 8226);

  entryspecialitei = gtk_entry_new ();
  gtk_widget_show (entryspecialitei);
  gtk_fixed_put (GTK_FIXED (fixed5), entryspecialitei, 192, 240);
  gtk_widget_set_size_request (entryspecialitei, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryspecialitei), 8226);

  entrynumrodetelephonei = gtk_entry_new ();
  gtk_widget_show (entrynumrodetelephonei);
  gtk_fixed_put (GTK_FIXED (fixed5), entrynumrodetelephonei, 192, 288);
  gtk_widget_set_size_request (entrynumrodetelephonei, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumrodetelephonei), 8226);

  buttonre = gtk_button_new ();
  gtk_widget_show (buttonre);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonre, 232, 376);
  gtk_widget_set_size_request (buttonre, 96, 32);

  alignment19 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment19);
  gtk_container_add (GTK_CONTAINER (buttonre), alignment19);

  hbox19 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox19);
  gtk_container_add (GTK_CONTAINER (alignment19), hbox19);

  image27 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image27);
  gtk_box_pack_start (GTK_BOX (hbox19), image27, FALSE, FALSE, 0);

  label58 = gtk_label_new (_("<span font_desc='medium italic'foreground='orange'> Retour :</span>"));
  gtk_widget_show (label58);
  gtk_box_pack_start (GTK_BOX (hbox19), label58, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label58), TRUE);

  buttonajouti = gtk_button_new ();
  gtk_widget_show (buttonajouti);
  gtk_fixed_put (GTK_FIXED (fixed5), buttonajouti, 224, 336);
  gtk_widget_set_size_request (buttonajouti, 112, 37);

  alignment10 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment10);
  gtk_container_add (GTK_CONTAINER (buttonajouti), alignment10);

  hbox10 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox10);
  gtk_container_add (GTK_CONTAINER (alignment10), hbox10);

  image11 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image11);
  gtk_box_pack_start (GTK_BOX (hbox10), image11, FALSE, FALSE, 0);

  label26 = gtk_label_new (_("<span font_desc='medium italic'foreground='blue'>Ajouter</span>"));
  gtk_widget_show (label26);
  gtk_box_pack_start (GTK_BOX (hbox10), label26, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label26), TRUE);

  image10 = gtk_image_new_from_stock ("gtk-add", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image10);
  gtk_fixed_put (GTK_FIXED (fixed5), image10, 224, 32);
  gtk_widget_set_size_request (image10, 77, 29);

  label22 = gtk_label_new (_("<span font_desc='medium italic'foreground='blue'> Identifiant : </span>"));
  gtk_widget_show (label22);
  gtk_fixed_put (GTK_FIXED (fixed5), label22, 64, 184);
  gtk_widget_set_size_request (label22, 128, 48);
  gtk_label_set_use_markup (GTK_LABEL (label22), TRUE);

  label21 = gtk_label_new (_("<span font_desc='medium italic'foreground='blue'>Pr\303\251nom        :</span>"));
  gtk_widget_show (label21);
  gtk_fixed_put (GTK_FIXED (fixed5), label21, 80, 136);
  gtk_widget_set_size_request (label21, 104, 41);
  gtk_label_set_use_markup (GTK_LABEL (label21), TRUE);

  label20 = gtk_label_new (_("<span font_desc='medium italic'foreground='blue'>Nom        :</span>"));
  gtk_widget_show (label20);
  gtk_fixed_put (GTK_FIXED (fixed5), label20, 96, 88);
  gtk_widget_set_size_request (label20, 89, 41);
  gtk_label_set_use_markup (GTK_LABEL (label20), TRUE);

  label23 = gtk_label_new (_("<span font_desc='medium italic'foreground='blue'> Sp\303\251cialit\303\251      : </span>"));
  gtk_widget_show (label23);
  gtk_fixed_put (GTK_FIXED (fixed5), label23, 40, 232);
  gtk_widget_set_size_request (label23, 152, 40);
  gtk_label_set_use_markup (GTK_LABEL (label23), TRUE);

  labelspecaj = gtk_label_new ("");
  gtk_widget_show (labelspecaj);
  gtk_fixed_put (GTK_FIXED (fixed5), labelspecaj, 368, 232);
  gtk_widget_set_size_request (labelspecaj, 160, 32);

  label24 = gtk_label_new (_("<span font_desc='medium italic'foreground='blue'> Numero de\n telephone  :</span>"));
  gtk_widget_show (label24);
  gtk_fixed_put (GTK_FIXED (fixed5), label24, 32, 264);
  gtk_widget_set_size_request (label24, 168, 80);
  gtk_label_set_use_markup (GTK_LABEL (label24), TRUE);

  label25 = gtk_label_new (_("<span font_desc='medium italic'foreground='black'> Ajouter un ouvrier   :</span>"));
  gtk_widget_show (label25);
  gtk_fixed_put (GTK_FIXED (fixed5), label25, 232, 24);
  gtk_widget_set_size_request (label25, 240, 40);
  gtk_label_set_use_markup (GTK_LABEL (label25), TRUE);

  labelnomaj = gtk_label_new ("");
  gtk_widget_show (labelnomaj);
  gtk_fixed_put (GTK_FIXED (fixed5), labelnomaj, 360, 96);
  gtk_widget_set_size_request (labelnomaj, 168, 32);

  labelprenomaj = gtk_label_new ("");
  gtk_widget_show (labelprenomaj);
  gtk_fixed_put (GTK_FIXED (fixed5), labelprenomaj, 352, 144);
  gtk_widget_set_size_request (labelprenomaj, 184, 32);

  labelidentaj = gtk_label_new ("");
  gtk_widget_show (labelidentaj);
  gtk_fixed_put (GTK_FIXED (fixed5), labelidentaj, 0, 0);
  gtk_widget_set_size_request (labelidentaj, 152, 40);

  labeltelaj = gtk_label_new ("");
  gtk_widget_show (labeltelaj);
  gtk_fixed_put (GTK_FIXED (fixed5), labeltelaj, 360, 288);
  gtk_widget_set_size_request (labeltelaj, 160, 32);

  label14 = gtk_label_new (_("<span font_desc='medium italic'foreground='blue'> Ajouter  :</span>"));
  gtk_widget_show (label14);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 0), label14);
  gtk_label_set_use_markup (GTK_LABEL (label14), TRUE);

  fixed10 = gtk_fixed_new ();
  gtk_widget_show (fixed10);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed10);

  entryidentifianti1 = gtk_entry_new ();
  gtk_widget_show (entryidentifianti1);
  gtk_fixed_put (GTK_FIXED (fixed10), entryidentifianti1, 120, 40);
  gtk_widget_set_size_request (entryidentifianti1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidentifianti1), 8226);

  entrynomi1 = gtk_entry_new ();
  gtk_widget_show (entrynomi1);
  gtk_fixed_put (GTK_FIXED (fixed10), entrynomi1, 192, 96);
  gtk_widget_set_size_request (entrynomi1, 160, 35);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynomi1), 8226);

  entryprenomi1 = gtk_entry_new ();
  gtk_widget_show (entryprenomi1);
  gtk_fixed_put (GTK_FIXED (fixed10), entryprenomi1, 192, 152);
  gtk_widget_set_size_request (entryprenomi1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryprenomi1), 8226);

  entryspecialitei1 = gtk_entry_new ();
  gtk_widget_show (entryspecialitei1);
  gtk_fixed_put (GTK_FIXED (fixed10), entryspecialitei1, 192, 248);
  gtk_widget_set_size_request (entryspecialitei1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryspecialitei1), 8226);

  entrynumdeteli1 = gtk_entry_new ();
  gtk_widget_show (entrynumdeteli1);
  gtk_fixed_put (GTK_FIXED (fixed10), entrynumdeteli1, 192, 288);
  gtk_widget_set_size_request (entrynumdeteli1, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entrynumdeteli1), 8226);

  infoi = gtk_label_new ("");
  gtk_widget_show (infoi);
  gtk_fixed_put (GTK_FIXED (fixed10), infoi, 112, 80);
  gtk_widget_set_size_request (infoi, 312, 25);

  entryidentifiantimodi = gtk_entry_new ();
  gtk_widget_show (entryidentifiantimodi);
  gtk_fixed_put (GTK_FIXED (fixed10), entryidentifiantimodi, 192, 200);
  gtk_widget_set_size_request (entryidentifiantimodi, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidentifiantimodi), 8226);

  buttonmodifieri = gtk_button_new ();
  gtk_widget_show (buttonmodifieri);
  gtk_fixed_put (GTK_FIXED (fixed10), buttonmodifieri, 208, 368);
  gtk_widget_set_size_request (buttonmodifieri, 104, 37);

  alignment15 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment15);
  gtk_container_add (GTK_CONTAINER (buttonmodifieri), alignment15);

  hbox15 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox15);
  gtk_container_add (GTK_CONTAINER (alignment15), hbox15);

  image17 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image17);
  gtk_box_pack_start (GTK_BOX (hbox15), image17, FALSE, FALSE, 0);

  label45 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'> Modifier</span>"));
  gtk_widget_show (label45);
  gtk_box_pack_start (GTK_BOX (hbox15), label45, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label45), TRUE);

  buttoninfoi = gtk_button_new ();
  gtk_widget_show (buttoninfoi);
  gtk_fixed_put (GTK_FIXED (fixed10), buttoninfoi, 304, 32);
  gtk_widget_set_size_request (buttoninfoi, 200, 37);

  alignment14 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment14);
  gtk_container_add (GTK_CONTAINER (buttoninfoi), alignment14);

  hbox14 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox14);
  gtk_container_add (GTK_CONTAINER (alignment14), hbox14);

  image16 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image16);
  gtk_box_pack_start (GTK_BOX (hbox14), image16, FALSE, FALSE, 0);

  label44 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'>Afficher les informations :</span>"));
  gtk_widget_show (label44);
  gtk_box_pack_start (GTK_BOX (hbox14), label44, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label44), TRUE);

  labelCheckNomModif = gtk_label_new ("");
  gtk_widget_show (labelCheckNomModif);
  gtk_fixed_put (GTK_FIXED (fixed10), labelCheckNomModif, 376, 96);
  gtk_widget_set_size_request (labelCheckNomModif, 97, 33);

  labelCheckPreomModif = gtk_label_new ("");
  gtk_widget_show (labelCheckPreomModif);
  gtk_fixed_put (GTK_FIXED (fixed10), labelCheckPreomModif, 376, 152);
  gtk_widget_set_size_request (labelCheckPreomModif, 89, 25);

  labelCheckidModif = gtk_label_new ("");
  gtk_widget_show (labelCheckidModif);
  gtk_fixed_put (GTK_FIXED (fixed10), labelCheckidModif, 368, 200);
  gtk_widget_set_size_request (labelCheckidModif, 144, 33);

  labelCheckspModif = gtk_label_new ("");
  gtk_widget_show (labelCheckspModif);
  gtk_fixed_put (GTK_FIXED (fixed10), labelCheckspModif, 360, 248);
  gtk_widget_set_size_request (labelCheckspModif, 168, 24);

  labelCheckTelModif = gtk_label_new ("");
  gtk_widget_show (labelCheckTelModif);
  gtk_fixed_put (GTK_FIXED (fixed10), labelCheckTelModif, 368, 288);
  gtk_widget_set_size_request (labelCheckTelModif, 128, 33);

  label39 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'>Identifiant :        :</span>"));
  gtk_widget_show (label39);
  gtk_fixed_put (GTK_FIXED (fixed10), label39, 0, 32);
  gtk_widget_set_size_request (label39, 144, 40);
  gtk_label_set_use_markup (GTK_LABEL (label39), TRUE);

  checkbuttonmodifieri = gtk_check_button_new_with_mnemonic (_("Etes-vous sur de vouloir effectuee ces modifications "));
  gtk_widget_show (checkbuttonmodifieri);
  gtk_fixed_put (GTK_FIXED (fixed10), checkbuttonmodifieri, 96, 328);
  gtk_widget_set_size_request (checkbuttonmodifieri, 424, 32);

  label43 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'> Numero de\n telephone  :</span>"));
  gtk_widget_show (label43);
  gtk_fixed_put (GTK_FIXED (fixed10), label43, 48, 264);
  gtk_widget_set_size_request (label43, 176, 72);
  gtk_label_set_use_markup (GTK_LABEL (label43), TRUE);

  label42 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'> Sp\303\251cialit\303\251      : </span>"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed10), label42, 88, 232);
  gtk_widget_set_size_request (label42, 104, 57);
  gtk_label_set_use_markup (GTK_LABEL (label42), TRUE);

  label56 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'> Identifiant : </span>\t\t"));
  gtk_widget_show (label56);
  gtk_fixed_put (GTK_FIXED (fixed10), label56, 96, 200);
  gtk_widget_set_size_request (label56, 105, 25);
  gtk_label_set_use_markup (GTK_LABEL (label56), TRUE);

  label41 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'>Pr\303\251nom        :</span>"));
  gtk_widget_show (label41);
  gtk_fixed_put (GTK_FIXED (fixed10), label41, 80, 152);
  gtk_widget_set_size_request (label41, 113, 32);
  gtk_label_set_use_markup (GTK_LABEL (label41), TRUE);

  label40 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'>Nom        :</span>"));
  gtk_widget_show (label40);
  gtk_fixed_put (GTK_FIXED (fixed10), label40, 80, 88);
  gtk_widget_set_size_request (label40, 120, 56);
  gtk_label_set_use_markup (GTK_LABEL (label40), TRUE);

  labelCheckidModif2 = gtk_label_new ("");
  gtk_widget_show (labelCheckidModif2);
  gtk_fixed_put (GTK_FIXED (fixed10), labelCheckidModif2, 112, 0);
  gtk_widget_set_size_request (labelCheckidModif2, 160, 33);

  label15 = gtk_label_new (_("<span font_desc='medium italic'foreground='brown'> Modifier  :</span>"));
  gtk_widget_show (label15);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 1), label15);
  gtk_label_set_use_markup (GTK_LABEL (label15), TRUE);

  fixed7 = gtk_fixed_new ();
  gtk_widget_show (fixed7);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed7);

  treeview1 = gtk_tree_view_new ();
  gtk_widget_show (treeview1);
  gtk_fixed_put (GTK_FIXED (fixed7), treeview1, 192, 144);
  gtk_widget_set_size_request (treeview1, 352, 168);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview1), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview1), TRUE);

  entryidsupp = gtk_entry_new ();
  gtk_widget_show (entryidsupp);
  gtk_fixed_put (GTK_FIXED (fixed7), entryidsupp, 160, 96);
  gtk_widget_set_size_request (entryidsupp, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidsupp), 8226);

  buttonsupprimeri = gtk_button_new ();
  gtk_widget_show (buttonsupprimeri);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonsupprimeri, 344, 88);
  gtk_widget_set_size_request (buttonsupprimeri, 112, 37);

  alignment11 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment11);
  gtk_container_add (GTK_CONTAINER (buttonsupprimeri), alignment11);

  hbox11 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox11);
  gtk_container_add (GTK_CONTAINER (alignment11), hbox11);

  image13 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image13);
  gtk_box_pack_start (GTK_BOX (hbox11), image13, FALSE, FALSE, 0);

  label33 = gtk_label_new (_("<span font_desc='medium italic'foreground='red'> Supprimer</span>"));
  gtk_widget_show (label33);
  gtk_box_pack_start (GTK_BOX (hbox11), label33, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label33), TRUE);

  label55 = gtk_label_new (_("<span font_desc='medium italic'foreground='red'> Entrer l'identifiant :</span>"));
  gtk_widget_show (label55);
  gtk_fixed_put (GTK_FIXED (fixed7), label55, 0, 88);
  gtk_widget_set_size_request (label55, 160, 40);
  gtk_label_set_use_markup (GTK_LABEL (label55), TRUE);

  image12 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image12);
  gtk_fixed_put (GTK_FIXED (fixed7), image12, 176, 24);
  gtk_widget_set_size_request (image12, 37, 32);

  image37 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image37);
  gtk_fixed_put (GTK_FIXED (fixed7), image37, 176, 24);
  gtk_widget_set_size_request (image37, 37, 32);

  image38 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image38);
  gtk_fixed_put (GTK_FIXED (fixed7), image38, 176, 24);
  gtk_widget_set_size_request (image38, 37, 32);

  label68 = gtk_label_new (_("<span font_desc='medium italic'foreground='red'> Cliquer deus fois pour supprimer !!!</span>"));
  gtk_widget_show (label68);
  gtk_fixed_put (GTK_FIXED (fixed7), label68, 232, 320);
  gtk_widget_set_size_request (label68, 272, 32);
  gtk_label_set_use_markup (GTK_LABEL (label68), TRUE);
  gtk_misc_set_alignment (GTK_MISC (label68), 0.49, 0.5);

  label32 = gtk_label_new (_("<span font_desc='medium italic'foreground='black'> Supprimer</span>"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed7), label32, 216, 24);
  gtk_widget_set_size_request (label32, 128, 32);
  gtk_label_set_use_markup (GTK_LABEL (label32), TRUE);

  buttonaffichsupp = gtk_button_new ();
  gtk_widget_show (buttonaffichsupp);
  gtk_fixed_put (GTK_FIXED (fixed7), buttonaffichsupp, 8, 176);
  gtk_widget_set_size_request (buttonaffichsupp, 168, 48);

  alignment17 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment17);
  gtk_container_add (GTK_CONTAINER (buttonaffichsupp), alignment17);

  hbox17 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox17);
  gtk_container_add (GTK_CONTAINER (alignment17), hbox17);

  image25 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image25);
  gtk_box_pack_start (GTK_BOX (hbox17), image25, FALSE, FALSE, 0);

  label54 = gtk_label_new (_("<span font_desc='medium italic'foreground='green'> Afficher tout :</span>"));
  gtk_widget_show (label54);
  gtk_box_pack_start (GTK_BOX (hbox17), label54, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label54), TRUE);

  label16 = gtk_label_new (_("<span font_desc='medium italic'foreground='red'> Afficher/Supprimer  :</span>"));
  gtk_widget_show (label16);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 2), label16);
  gtk_label_set_use_markup (GTK_LABEL (label16), TRUE);

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed8);

  entryidentifianti2 = gtk_entry_new ();
  gtk_widget_show (entryidentifianti2);
  gtk_fixed_put (GTK_FIXED (fixed8), entryidentifianti2, 168, 96);
  gtk_widget_set_size_request (entryidentifianti2, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidentifianti2), 8226);

  infoi2 = gtk_label_new ("");
  gtk_widget_show (infoi2);
  gtk_fixed_put (GTK_FIXED (fixed8), infoi2, 104, 224);
  gtk_widget_set_size_request (infoi2, 240, 65);

  treeview2 = gtk_tree_view_new ();
  gtk_widget_show (treeview2);
  gtk_fixed_put (GTK_FIXED (fixed8), treeview2, 184, 192);
  gtk_widget_set_size_request (treeview2, 376, 176);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview2), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview2), TRUE);

  buttonchercheri = gtk_button_new ();
  gtk_widget_show (buttonchercheri);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonchercheri, 336, 88);
  gtk_widget_set_size_request (buttonchercheri, 112, 45);

  alignment13 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment13);
  gtk_container_add (GTK_CONTAINER (buttonchercheri), alignment13);

  hbox13 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox13);
  gtk_container_add (GTK_CONTAINER (alignment13), hbox13);

  image15 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image15);
  gtk_box_pack_start (GTK_BOX (hbox13), image15, FALSE, FALSE, 0);

  label37 = gtk_label_new (_(" <span font_desc='medium italic'foreground='purple'> Chercher </span>"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox13), label37, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label37), TRUE);

  image20 = gtk_image_new_from_stock ("gtk-find", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image20);
  gtk_fixed_put (GTK_FIXED (fixed8), image20, 200, 32);
  gtk_widget_set_size_request (image20, 21, 21);

  label31 = gtk_label_new (_("<span font_desc='medium italic'foreground='purple'> Identifiant :  </span>"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 48, 80);
  gtk_widget_set_size_request (label31, 129, 57);
  gtk_label_set_use_markup (GTK_LABEL (label31), TRUE);

  buttonretourchercher = gtk_button_new ();
  gtk_widget_show (buttonretourchercher);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonretourchercher, 456, 104);
  gtk_widget_set_size_request (buttonretourchercher, 96, 24);

  alignment20 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment20);
  gtk_container_add (GTK_CONTAINER (buttonretourchercher), alignment20);

  hbox20 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox20);
  gtk_container_add (GTK_CONTAINER (alignment20), hbox20);

  image28 = gtk_image_new_from_stock ("gtk-undo", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image28);
  gtk_box_pack_start (GTK_BOX (hbox20), image28, FALSE, FALSE, 0);

  label64 = gtk_label_new (_("<span font_desc='medium italic'foreground='orange'> retour </span>"));
  gtk_widget_show (label64);
  gtk_box_pack_start (GTK_BOX (hbox20), label64, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label64), TRUE);

  label53 = gtk_label_new (_("<span font_desc='medium italic'foreground='black'> Chercher    :</span>"));
  gtk_widget_show (label53);
  gtk_fixed_put (GTK_FIXED (fixed8), label53, 224, 24);
  gtk_widget_set_size_request (label53, 128, 33);
  gtk_label_set_use_markup (GTK_LABEL (label53), TRUE);

  buttonAffichecherch = gtk_button_new ();
  gtk_widget_show (buttonAffichecherch);
  gtk_fixed_put (GTK_FIXED (fixed8), buttonAffichecherch, 8, 216);
  gtk_widget_set_size_request (buttonAffichecherch, 160, 40);

  alignment18 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment18);
  gtk_container_add (GTK_CONTAINER (buttonAffichecherch), alignment18);

  hbox18 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox18);
  gtk_container_add (GTK_CONTAINER (alignment18), hbox18);

  image26 = gtk_image_new_from_stock ("gtk-justify-fill", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image26);
  gtk_box_pack_start (GTK_BOX (hbox18), image26, FALSE, FALSE, 0);

  label57 = gtk_label_new (_("<span font_desc='medium italic'foreground='green'> Afficher tout : </span>"));
  gtk_widget_show (label57);
  gtk_box_pack_start (GTK_BOX (hbox18), label57, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label57), TRUE);

  label17 = gtk_label_new (_("<span font_desc='medium italic'foreground='purple'> Chercher   :</span>"));
  gtk_widget_show (label17);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 3), label17);
  gtk_label_set_use_markup (GTK_LABEL (label17), TRUE);

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (notebook1), fixed9);

  entryidentifianti3 = gtk_entry_new ();
  gtk_widget_show (entryidentifianti3);
  gtk_fixed_put (GTK_FIXED (fixed9), entryidentifianti3, 120, 88);
  gtk_widget_set_size_request (entryidentifianti3, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entryidentifianti3), 8226);

  treeview3 = gtk_tree_view_new ();
  gtk_widget_show (treeview3);
  gtk_fixed_put (GTK_FIXED (fixed9), treeview3, 272, 280);
  gtk_widget_set_size_request (treeview3, 304, 128);
  gtk_tree_view_set_rules_hint (GTK_TREE_VIEW (treeview3), TRUE);
  gtk_tree_view_set_reorderable (GTK_TREE_VIEW (treeview3), TRUE);

  buttonconfirmeri = gtk_button_new ();
  gtk_widget_show (buttonconfirmeri);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonconfirmeri, 216, 240);
  gtk_widget_set_size_request (buttonconfirmeri, 128, 32);

  alignment16 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment16);
  gtk_container_add (GTK_CONTAINER (buttonconfirmeri), alignment16);

  hbox16 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox16);
  gtk_container_add (GTK_CONTAINER (alignment16), hbox16);

  image19 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image19);
  gtk_box_pack_start (GTK_BOX (hbox16), image19, FALSE, FALSE, 0);

  label52 = gtk_label_new (_("<span font_desc='medium italic'foreground='green'>  Confirmer  :</span>"));
  gtk_widget_show (label52);
  gtk_box_pack_start (GTK_BOX (hbox16), label52, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label52), TRUE);

  label50 = gtk_label_new (_("<span font_desc='medium italic'foreground='darkgoldenrod'>  Identifiant    :</span>"));
  gtk_widget_show (label50);
  gtk_fixed_put (GTK_FIXED (fixed9), label50, 0, 88);
  gtk_widget_set_size_request (label50, 120, 25);
  gtk_label_set_use_markup (GTK_LABEL (label50), TRUE);

  label49 = gtk_label_new (_("<span font_desc='medium italic'foreground='black'>  Date :   :</span>"));
  gtk_widget_show (label49);
  gtk_fixed_put (GTK_FIXED (fixed9), label49, 8, 184);
  gtk_widget_set_size_request (label49, 104, 48);
  gtk_label_set_use_markup (GTK_LABEL (label49), TRUE);

  label65 = gtk_label_new (_("<span font_desc='medium italic'foreground='navy'>  Ann\303\251e   :</span>"));
  gtk_widget_show (label65);
  gtk_fixed_put (GTK_FIXED (fixed9), label65, 344, 152);
  gtk_widget_set_size_request (label65, 96, 33);
  gtk_label_set_use_markup (GTK_LABEL (label65), TRUE);

  comboboxentryannee3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryannee3);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentryannee3, 352, 192);
  gtk_widget_set_size_request (comboboxentryannee3, 88, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryannee3), _("2020"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryannee3), _("2021"));

  comboboxentrymois3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentrymois3);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentrymois3, 240, 192);
  gtk_widget_set_size_request (comboboxentrymois3, 85, 37);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentrymois3), _("12"));

  comboboxentryjour3 = gtk_combo_box_entry_new_text ();
  gtk_widget_show (comboboxentryjour3);
  gtk_fixed_put (GTK_FIXED (fixed9), comboboxentryjour3, 120, 192);
  gtk_widget_set_size_request (comboboxentryjour3, 80, 40);
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("01"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("02"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("03"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("04"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("05"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("06"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("07"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("08"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("09"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("10"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("11"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("12"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("13"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("14"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("15"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("16"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("17"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("18"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("19"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("20"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("21"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("22"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("23"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("24"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("25"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("26"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("27"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("28"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("29"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("30"));
  gtk_combo_box_append_text (GTK_COMBO_BOX (comboboxentryjour3), _("31"));

  label47 = gtk_label_new (_("<span font_desc='medium italic'foreground='navy'>  Jour   :</span>"));
  gtk_widget_show (label47);
  gtk_fixed_put (GTK_FIXED (fixed9), label47, 128, 152);
  gtk_widget_set_size_request (label47, 65, 33);
  gtk_label_set_use_markup (GTK_LABEL (label47), TRUE);

  label48 = gtk_label_new (_("<span font_desc='medium italic'foreground='navy'>  Mois   :</span>"));
  gtk_widget_show (label48);
  gtk_fixed_put (GTK_FIXED (fixed9), label48, 240, 152);
  gtk_widget_set_size_request (label48, 73, 33);
  gtk_label_set_use_markup (GTK_LABEL (label48), TRUE);

  buttonafficherab = gtk_button_new ();
  gtk_widget_show (buttonafficherab);
  gtk_fixed_put (GTK_FIXED (fixed9), buttonafficherab, 8, 320);
  gtk_widget_set_size_request (buttonafficherab, 240, 56);

  alignment21 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment21);
  gtk_container_add (GTK_CONTAINER (buttonafficherab), alignment21);

  hbox21 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox21);
  gtk_container_add (GTK_CONTAINER (alignment21), hbox21);

  image35 = gtk_image_new_from_stock ("gtk-info", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image35);
  gtk_box_pack_start (GTK_BOX (hbox21), image35, FALSE, FALSE, 0);

  label66 = gtk_label_new (_("<span font_desc='medium italic'foreground='green'> Afficher liste  d'absence ------>   :</span>"));
  gtk_widget_show (label66);
  gtk_box_pack_start (GTK_BOX (hbox21), label66, FALSE, FALSE, 0);
  gtk_label_set_use_markup (GTK_LABEL (label66), TRUE);

  label51 = gtk_label_new (_("<span font_desc='medium italic'foreground='black'>  Marquer l'absence  :</span>"));
  gtk_widget_show (label51);
  gtk_fixed_put (GTK_FIXED (fixed9), label51, 80, 8);
  gtk_widget_set_size_request (label51, 464, 56);
  gtk_label_set_use_markup (GTK_LABEL (label51), TRUE);

  image18 = gtk_image_new_from_stock ("gtk-apply", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image18);
  gtk_fixed_put (GTK_FIXED (fixed9), image18, 208, 24);
  gtk_widget_set_size_request (image18, 21, 21);

  label18 = gtk_label_new (_("<span font_desc='medium italic'foreground='darkgoldenrod'>  Marquer les absences   :</span>"));
  gtk_widget_show (label18);
  gtk_notebook_set_tab_label (GTK_NOTEBOOK (notebook1), gtk_notebook_get_nth_page (GTK_NOTEBOOK (notebook1), 4), label18);
  gtk_label_set_use_markup (GTK_LABEL (label18), TRUE);

  image42 = create_pixmap (Gestion_d_ouvriers, "99946F345ACEE21A25.jpeg");
  gtk_widget_show (image42);
  gtk_fixed_put (GTK_FIXED (Gestion_d_ouvrier_), image42, 576, 208);
  gtk_widget_set_size_request (image42, 64, 352);

  g_signal_connect ((gpointer) buttonre, "clicked",
                    G_CALLBACK (on_buttonre_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonajouti, "clicked",
                    G_CALLBACK (on_buttonajouti_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonmodifieri, "clicked",
                    G_CALLBACK (on_buttonmodifieri_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttoninfoi, "clicked",
                    G_CALLBACK (on_buttoninfoi_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview1, "row_activated",
                    G_CALLBACK (on_treeview1_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonsupprimeri, "clicked",
                    G_CALLBACK (on_buttonsupprimeri_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonaffichsupp, "clicked",
                    G_CALLBACK (on_buttonaffichsupp_clicked),
                    NULL);
  g_signal_connect ((gpointer) treeview2, "row_activated",
                    G_CALLBACK (on_treeview2_row_activated),
                    NULL);
  g_signal_connect ((gpointer) buttonchercheri, "clicked",
                    G_CALLBACK (on_buttonchercheri_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonretourchercher, "clicked",
                    G_CALLBACK (on_buttonretourchercher_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonAffichecherch, "clicked",
                    G_CALLBACK (on_buttonAffichecherch_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonconfirmeri, "clicked",
                    G_CALLBACK (on_buttonconfirmeri_clicked),
                    NULL);
  g_signal_connect ((gpointer) buttonafficherab, "clicked",
                    G_CALLBACK (on_buttonafficherab_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (Gestion_d_ouvriers, Gestion_d_ouvriers, "Gestion_d_ouvriers");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, Gestion_d_ouvrier_, "Gestion_d_ouvrier_");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image41, "image41");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label19, "label19");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, notebook1, "notebook1");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, fixed5, "fixed5");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entrynomi, "entrynomi");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryprenomi, "entryprenomi");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryidentifianti, "entryidentifianti");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryspecialitei, "entryspecialitei");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entrynumrodetelephonei, "entrynumrodetelephonei");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonre, "buttonre");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment19, "alignment19");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox19, "hbox19");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image27, "image27");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label58, "label58");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonajouti, "buttonajouti");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment10, "alignment10");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox10, "hbox10");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image11, "image11");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label26, "label26");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image10, "image10");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label22, "label22");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label21, "label21");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label20, "label20");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label23, "label23");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelspecaj, "labelspecaj");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label24, "label24");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label25, "label25");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelnomaj, "labelnomaj");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelprenomaj, "labelprenomaj");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelidentaj, "labelidentaj");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labeltelaj, "labeltelaj");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label14, "label14");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, fixed10, "fixed10");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryidentifianti1, "entryidentifianti1");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entrynomi1, "entrynomi1");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryprenomi1, "entryprenomi1");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryspecialitei1, "entryspecialitei1");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entrynumdeteli1, "entrynumdeteli1");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, infoi, "infoi");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryidentifiantimodi, "entryidentifiantimodi");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonmodifieri, "buttonmodifieri");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment15, "alignment15");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox15, "hbox15");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image17, "image17");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label45, "label45");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttoninfoi, "buttoninfoi");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment14, "alignment14");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox14, "hbox14");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image16, "image16");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label44, "label44");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelCheckNomModif, "labelCheckNomModif");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelCheckPreomModif, "labelCheckPreomModif");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelCheckidModif, "labelCheckidModif");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelCheckspModif, "labelCheckspModif");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelCheckTelModif, "labelCheckTelModif");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label39, "label39");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, checkbuttonmodifieri, "checkbuttonmodifieri");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label43, "label43");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label42, "label42");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label56, "label56");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label41, "label41");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label40, "label40");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, labelCheckidModif2, "labelCheckidModif2");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label15, "label15");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, fixed7, "fixed7");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, treeview1, "treeview1");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryidsupp, "entryidsupp");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonsupprimeri, "buttonsupprimeri");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment11, "alignment11");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox11, "hbox11");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image13, "image13");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label33, "label33");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label55, "label55");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image12, "image12");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image37, "image37");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image38, "image38");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label68, "label68");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label32, "label32");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonaffichsupp, "buttonaffichsupp");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment17, "alignment17");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox17, "hbox17");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image25, "image25");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label54, "label54");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label16, "label16");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryidentifianti2, "entryidentifianti2");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, infoi2, "infoi2");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, treeview2, "treeview2");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonchercheri, "buttonchercheri");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment13, "alignment13");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox13, "hbox13");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image15, "image15");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label37, "label37");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image20, "image20");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label31, "label31");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonretourchercher, "buttonretourchercher");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment20, "alignment20");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox20, "hbox20");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image28, "image28");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label64, "label64");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label53, "label53");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonAffichecherch, "buttonAffichecherch");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment18, "alignment18");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox18, "hbox18");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image26, "image26");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label57, "label57");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label17, "label17");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, entryidentifianti3, "entryidentifianti3");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, treeview3, "treeview3");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonconfirmeri, "buttonconfirmeri");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment16, "alignment16");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox16, "hbox16");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image19, "image19");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label52, "label52");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label50, "label50");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label49, "label49");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label65, "label65");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, comboboxentryannee3, "comboboxentryannee3");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, comboboxentrymois3, "comboboxentrymois3");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, comboboxentryjour3, "comboboxentryjour3");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label47, "label47");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label48, "label48");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, buttonafficherab, "buttonafficherab");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, alignment21, "alignment21");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, hbox21, "hbox21");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image35, "image35");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label66, "label66");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label51, "label51");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image18, "image18");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, label18, "label18");
  GLADE_HOOKUP_OBJECT (Gestion_d_ouvriers, image42, "image42");

  return Gestion_d_ouvriers;
}

