/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

GtkWidget* create_authentification (void);
GtkWidget* create_administrateur (void);
GtkWidget* create_Tableu_de_bord_ (void);
GtkWidget* create_Gestion_d_ouvriers (void);
