/*
 * DO NOT EDIT THIS FILE - it is generated by Glade.
 */

#ifdef HAVE_CONFIG_H
#  include <config.h>
#endif

#include <sys/types.h>
#include <sys/stat.h>
#include <unistd.h>
#include <string.h>
#include <stdio.h>

#include <gdk/gdkkeysyms.h>
#include <gtk/gtk.h>

#include "callbacks.h"
#include "interface.h"
#include "support.h"

#define GLADE_HOOKUP_OBJECT(component,widget,name) \
  g_object_set_data_full (G_OBJECT (component), name, \
    gtk_widget_ref (widget), (GDestroyNotify) gtk_widget_unref)

#define GLADE_HOOKUP_OBJECT_NO_REF(component,widget,name) \
  g_object_set_data (G_OBJECT (component), name, widget)

GtkWidget*
create_windowmateriel (void)
{
  GtkWidget *windowmateriel;
  GtkWidget *fixed8;
  GtkWidget *treemateriel;
  GtkWidget *identry;
  GtkWidget *label29;
  GtkWidget *nomentry;
  GtkWidget *label30;
  GtkWidget *typeentry;
  GtkWidget *label31;
  GtkWidget *etatentry;
  GtkWidget *label32;
  GtkWidget *entry17;
  GtkWidget *label33;
  GtkWidget *label35;
  GtkObject *quantiteentry_adj;
  GtkWidget *quantiteentry;
  GtkWidget *affichage;
  GtkWidget *alignment2;
  GtkWidget *hbox2;
  GtkWidget *image2;
  GtkWidget *label37;
  GtkWidget *supprimer;
  GtkWidget *alignment3;
  GtkWidget *hbox3;
  GtkWidget *image3;
  GtkWidget *label38;
  GtkWidget *modifier;
  GtkWidget *alignment4;
  GtkWidget *hbox4;
  GtkWidget *image4;
  GtkWidget *label39;
  GtkWidget *enregistrermodification;
  GtkWidget *alignment5;
  GtkWidget *hbox5;
  GtkWidget *image5;
  GtkWidget *label40;
  GtkWidget *ajouter;
  GtkWidget *alignment6;
  GtkWidget *hbox6;
  GtkWidget *image6;
  GtkWidget *label41;
  GtkWidget *refresh;
  GtkWidget *alignment1;
  GtkWidget *hbox1;
  GtkWidget *image1;
  GtkWidget *label36;
  GtkWidget *message;

  windowmateriel = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (windowmateriel), _("window1"));

  fixed8 = gtk_fixed_new ();
  gtk_widget_show (fixed8);
  gtk_container_add (GTK_CONTAINER (windowmateriel), fixed8);

  treemateriel = gtk_tree_view_new ();
  gtk_widget_show (treemateriel);
  gtk_fixed_put (GTK_FIXED (fixed8), treemateriel, 104, 96);
  gtk_widget_set_size_request (treemateriel, 300, 200);

  identry = gtk_entry_new ();
  gtk_widget_show (identry);
  gtk_fixed_put (GTK_FIXED (fixed8), identry, 64, 336);
  gtk_widget_set_size_request (identry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (identry), 8226);

  label29 = gtk_label_new (_("id"));
  gtk_widget_show (label29);
  gtk_fixed_put (GTK_FIXED (fixed8), label29, 72, 304);
  gtk_widget_set_size_request (label29, 49, 17);

  nomentry = gtk_entry_new ();
  gtk_widget_show (nomentry);
  gtk_fixed_put (GTK_FIXED (fixed8), nomentry, 272, 336);
  gtk_widget_set_size_request (nomentry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (nomentry), 8226);

  label30 = gtk_label_new (_("nom "));
  gtk_widget_show (label30);
  gtk_fixed_put (GTK_FIXED (fixed8), label30, 288, 312);
  gtk_widget_set_size_request (label30, 49, 17);

  typeentry = gtk_entry_new ();
  gtk_widget_show (typeentry);
  gtk_fixed_put (GTK_FIXED (fixed8), typeentry, 472, 336);
  gtk_widget_set_size_request (typeentry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (typeentry), 8226);

  label31 = gtk_label_new (_("type"));
  gtk_widget_show (label31);
  gtk_fixed_put (GTK_FIXED (fixed8), label31, 512, 312);
  gtk_widget_set_size_request (label31, 49, 17);

  etatentry = gtk_entry_new ();
  gtk_widget_show (etatentry);
  gtk_fixed_put (GTK_FIXED (fixed8), etatentry, 56, 400);
  gtk_widget_set_size_request (etatentry, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (etatentry), 8226);

  label32 = gtk_label_new (_("etat"));
  gtk_widget_show (label32);
  gtk_fixed_put (GTK_FIXED (fixed8), label32, 80, 376);
  gtk_widget_set_size_request (label32, 49, 17);

  entry17 = gtk_entry_new ();
  gtk_widget_show (entry17);
  gtk_fixed_put (GTK_FIXED (fixed8), entry17, 608, 88);
  gtk_widget_set_size_request (entry17, 160, 27);
  gtk_entry_set_invisible_char (GTK_ENTRY (entry17), 8226);

  label33 = gtk_label_new (_("rechercher "));
  gtk_widget_show (label33);
  gtk_fixed_put (GTK_FIXED (fixed8), label33, 624, 56);
  gtk_widget_set_size_request (label33, 104, 24);

  label35 = gtk_label_new (_("quantit\303\251"));
  gtk_widget_show (label35);
  gtk_fixed_put (GTK_FIXED (fixed8), label35, 288, 376);
  gtk_widget_set_size_request (label35, 96, 16);

  quantiteentry_adj = gtk_adjustment_new (1, 1, 1000, 1, 10, 10);
  quantiteentry = gtk_spin_button_new (GTK_ADJUSTMENT (quantiteentry_adj), 1, 0);
  gtk_widget_show (quantiteentry);
  gtk_fixed_put (GTK_FIXED (fixed8), quantiteentry, 272, 400);
  gtk_widget_set_size_request (quantiteentry, 160, 32);

  affichage = gtk_button_new ();
  gtk_widget_show (affichage);
  gtk_fixed_put (GTK_FIXED (fixed8), affichage, 48, 24);
  gtk_widget_set_size_request (affichage, 232, 40);

  alignment2 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment2);
  gtk_container_add (GTK_CONTAINER (affichage), alignment2);

  hbox2 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox2);
  gtk_container_add (GTK_CONTAINER (alignment2), hbox2);

  image2 = gtk_image_new_from_stock ("gtk-index", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image2);
  gtk_box_pack_start (GTK_BOX (hbox2), image2, FALSE, FALSE, 0);

  label37 = gtk_label_new_with_mnemonic (_("afficher les materielles"));
  gtk_widget_show (label37);
  gtk_box_pack_start (GTK_BOX (hbox2), label37, FALSE, FALSE, 0);

  supprimer = gtk_button_new ();
  gtk_widget_show (supprimer);
  gtk_fixed_put (GTK_FIXED (fixed8), supprimer, 632, 128);
  gtk_widget_set_size_request (supprimer, 120, 32);

  alignment3 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment3);
  gtk_container_add (GTK_CONTAINER (supprimer), alignment3);

  hbox3 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox3);
  gtk_container_add (GTK_CONTAINER (alignment3), hbox3);

  image3 = gtk_image_new_from_stock ("gtk-delete", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image3);
  gtk_box_pack_start (GTK_BOX (hbox3), image3, FALSE, FALSE, 0);

  label38 = gtk_label_new_with_mnemonic (_("supprimer"));
  gtk_widget_show (label38);
  gtk_box_pack_start (GTK_BOX (hbox3), label38, FALSE, FALSE, 0);

  modifier = gtk_button_new ();
  gtk_widget_show (modifier);
  gtk_fixed_put (GTK_FIXED (fixed8), modifier, 632, 168);
  gtk_widget_set_size_request (modifier, 120, 32);

  alignment4 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment4);
  gtk_container_add (GTK_CONTAINER (modifier), alignment4);

  hbox4 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox4);
  gtk_container_add (GTK_CONTAINER (alignment4), hbox4);

  image4 = gtk_image_new_from_stock ("gtk-edit", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image4);
  gtk_box_pack_start (GTK_BOX (hbox4), image4, FALSE, FALSE, 0);

  label39 = gtk_label_new_with_mnemonic (_("modifier"));
  gtk_widget_show (label39);
  gtk_box_pack_start (GTK_BOX (hbox4), label39, FALSE, FALSE, 0);

  enregistrermodification = gtk_button_new ();
  gtk_widget_show (enregistrermodification);
  gtk_fixed_put (GTK_FIXED (fixed8), enregistrermodification, 464, 416);
  gtk_widget_set_size_request (enregistrermodification, 200, 32);

  alignment5 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment5);
  gtk_container_add (GTK_CONTAINER (enregistrermodification), alignment5);

  hbox5 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox5);
  gtk_container_add (GTK_CONTAINER (alignment5), hbox5);

  image5 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image5);
  gtk_box_pack_start (GTK_BOX (hbox5), image5, FALSE, FALSE, 0);

  label40 = gtk_label_new_with_mnemonic (_("enregistrer la modification"));
  gtk_widget_show (label40);
  gtk_box_pack_start (GTK_BOX (hbox5), label40, FALSE, FALSE, 0);

  ajouter = gtk_button_new ();
  gtk_widget_show (ajouter);
  gtk_fixed_put (GTK_FIXED (fixed8), ajouter, 512, 376);
  gtk_widget_set_size_request (ajouter, 96, 32);

  alignment6 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment6);
  gtk_container_add (GTK_CONTAINER (ajouter), alignment6);

  hbox6 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox6);
  gtk_container_add (GTK_CONTAINER (alignment6), hbox6);

  image6 = gtk_image_new_from_stock ("gtk-floppy", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image6);
  gtk_box_pack_start (GTK_BOX (hbox6), image6, FALSE, FALSE, 0);

  label41 = gtk_label_new_with_mnemonic (_("ajouter"));
  gtk_widget_show (label41);
  gtk_box_pack_start (GTK_BOX (hbox6), label41, FALSE, FALSE, 0);

  refresh = gtk_button_new ();
  gtk_widget_show (refresh);
  gtk_fixed_put (GTK_FIXED (fixed8), refresh, 320, 24);
  gtk_widget_set_size_request (refresh, 80, 40);

  alignment1 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment1);
  gtk_container_add (GTK_CONTAINER (refresh), alignment1);

  hbox1 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox1);
  gtk_container_add (GTK_CONTAINER (alignment1), hbox1);

  image1 = gtk_image_new_from_stock ("gtk-refresh", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image1);
  gtk_box_pack_start (GTK_BOX (hbox1), image1, FALSE, FALSE, 0);

  label36 = gtk_label_new_with_mnemonic (_("refresh"));
  gtk_widget_show (label36);
  gtk_box_pack_start (GTK_BOX (hbox1), label36, FALSE, FALSE, 0);

  message = gtk_label_new ("");
  gtk_widget_show (message);
  gtk_fixed_put (GTK_FIXED (fixed8), message, 552, 224);
  gtk_widget_set_size_request (message, 272, 40);

  g_signal_connect ((gpointer) affichage, "clicked",
                    G_CALLBACK (on_affichage_clicked),
                    NULL);
  g_signal_connect ((gpointer) supprimer, "clicked",
                    G_CALLBACK (on_supprimer_clicked),
                    NULL);
  g_signal_connect ((gpointer) modifier, "clicked",
                    G_CALLBACK (on_modifier_clicked),
                    NULL);
  g_signal_connect ((gpointer) enregistrermodification, "clicked",
                    G_CALLBACK (on_enregistrermodification_clicked),
                    NULL);
  g_signal_connect ((gpointer) ajouter, "clicked",
                    G_CALLBACK (on_ajouter_clicked),
                    NULL);
  g_signal_connect ((gpointer) refresh, "clicked",
                    G_CALLBACK (on_refresh_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (windowmateriel, windowmateriel, "windowmateriel");
  GLADE_HOOKUP_OBJECT (windowmateriel, fixed8, "fixed8");
  GLADE_HOOKUP_OBJECT (windowmateriel, treemateriel, "treemateriel");
  GLADE_HOOKUP_OBJECT (windowmateriel, identry, "identry");
  GLADE_HOOKUP_OBJECT (windowmateriel, label29, "label29");
  GLADE_HOOKUP_OBJECT (windowmateriel, nomentry, "nomentry");
  GLADE_HOOKUP_OBJECT (windowmateriel, label30, "label30");
  GLADE_HOOKUP_OBJECT (windowmateriel, typeentry, "typeentry");
  GLADE_HOOKUP_OBJECT (windowmateriel, label31, "label31");
  GLADE_HOOKUP_OBJECT (windowmateriel, etatentry, "etatentry");
  GLADE_HOOKUP_OBJECT (windowmateriel, label32, "label32");
  GLADE_HOOKUP_OBJECT (windowmateriel, entry17, "entry17");
  GLADE_HOOKUP_OBJECT (windowmateriel, label33, "label33");
  GLADE_HOOKUP_OBJECT (windowmateriel, label35, "label35");
  GLADE_HOOKUP_OBJECT (windowmateriel, quantiteentry, "quantiteentry");
  GLADE_HOOKUP_OBJECT (windowmateriel, affichage, "affichage");
  GLADE_HOOKUP_OBJECT (windowmateriel, alignment2, "alignment2");
  GLADE_HOOKUP_OBJECT (windowmateriel, hbox2, "hbox2");
  GLADE_HOOKUP_OBJECT (windowmateriel, image2, "image2");
  GLADE_HOOKUP_OBJECT (windowmateriel, label37, "label37");
  GLADE_HOOKUP_OBJECT (windowmateriel, supprimer, "supprimer");
  GLADE_HOOKUP_OBJECT (windowmateriel, alignment3, "alignment3");
  GLADE_HOOKUP_OBJECT (windowmateriel, hbox3, "hbox3");
  GLADE_HOOKUP_OBJECT (windowmateriel, image3, "image3");
  GLADE_HOOKUP_OBJECT (windowmateriel, label38, "label38");
  GLADE_HOOKUP_OBJECT (windowmateriel, modifier, "modifier");
  GLADE_HOOKUP_OBJECT (windowmateriel, alignment4, "alignment4");
  GLADE_HOOKUP_OBJECT (windowmateriel, hbox4, "hbox4");
  GLADE_HOOKUP_OBJECT (windowmateriel, image4, "image4");
  GLADE_HOOKUP_OBJECT (windowmateriel, label39, "label39");
  GLADE_HOOKUP_OBJECT (windowmateriel, enregistrermodification, "enregistrermodification");
  GLADE_HOOKUP_OBJECT (windowmateriel, alignment5, "alignment5");
  GLADE_HOOKUP_OBJECT (windowmateriel, hbox5, "hbox5");
  GLADE_HOOKUP_OBJECT (windowmateriel, image5, "image5");
  GLADE_HOOKUP_OBJECT (windowmateriel, label40, "label40");
  GLADE_HOOKUP_OBJECT (windowmateriel, ajouter, "ajouter");
  GLADE_HOOKUP_OBJECT (windowmateriel, alignment6, "alignment6");
  GLADE_HOOKUP_OBJECT (windowmateriel, hbox6, "hbox6");
  GLADE_HOOKUP_OBJECT (windowmateriel, image6, "image6");
  GLADE_HOOKUP_OBJECT (windowmateriel, label41, "label41");
  GLADE_HOOKUP_OBJECT (windowmateriel, refresh, "refresh");
  GLADE_HOOKUP_OBJECT (windowmateriel, alignment1, "alignment1");
  GLADE_HOOKUP_OBJECT (windowmateriel, hbox1, "hbox1");
  GLADE_HOOKUP_OBJECT (windowmateriel, image1, "image1");
  GLADE_HOOKUP_OBJECT (windowmateriel, label36, "label36");
  GLADE_HOOKUP_OBJECT (windowmateriel, message, "message");

  return windowmateriel;
}

GtkWidget*
create_window2 (void)
{
  GtkWidget *window2;
  GtkWidget *fixed9;
  GtkWidget *label42;
  GtkWidget *buttondaliaffiche;
  GtkWidget *alignment7;
  GtkWidget *hbox7;
  GtkWidget *image7;
  GtkWidget *labeldaliseche;
  GtkWidget *textviewAnseche;

  window2 = gtk_window_new (GTK_WINDOW_TOPLEVEL);
  gtk_window_set_title (GTK_WINDOW (window2), _("window2"));

  fixed9 = gtk_fixed_new ();
  gtk_widget_show (fixed9);
  gtk_container_add (GTK_CONTAINER (window2), fixed9);

  label42 = gtk_label_new (_("l'ann\303\251e la plus s\341\272\277che"));
  gtk_widget_show (label42);
  gtk_fixed_put (GTK_FIXED (fixed9), label42, 16, 32);
  gtk_widget_set_size_request (label42, 152, 25);
  gtk_misc_set_alignment (GTK_MISC (label42), 0.5, 0.22);

  buttondaliaffiche = gtk_button_new ();
  gtk_widget_show (buttondaliaffiche);
  gtk_fixed_put (GTK_FIXED (fixed9), buttondaliaffiche, 144, 112);
  gtk_widget_set_size_request (buttondaliaffiche, 154, 29);

  alignment7 = gtk_alignment_new (0.5, 0.5, 0, 0);
  gtk_widget_show (alignment7);
  gtk_container_add (GTK_CONTAINER (buttondaliaffiche), alignment7);

  hbox7 = gtk_hbox_new (FALSE, 2);
  gtk_widget_show (hbox7);
  gtk_container_add (GTK_CONTAINER (alignment7), hbox7);

  image7 = gtk_image_new_from_stock ("gtk-justify-center", GTK_ICON_SIZE_BUTTON);
  gtk_widget_show (image7);
  gtk_box_pack_start (GTK_BOX (hbox7), image7, FALSE, FALSE, 0);

  labeldaliseche = gtk_label_new_with_mnemonic (_("Affiche l'annee"));
  gtk_widget_show (labeldaliseche);
  gtk_box_pack_start (GTK_BOX (hbox7), labeldaliseche, FALSE, FALSE, 0);

  textviewAnseche = gtk_label_new ("");
  gtk_widget_show (textviewAnseche);
  gtk_fixed_put (GTK_FIXED (fixed9), textviewAnseche, 184, 32);
  gtk_widget_set_size_request (textviewAnseche, 168, 24);

  g_signal_connect ((gpointer) buttondaliaffiche, "clicked",
                    G_CALLBACK (on_buttondaliaffiche_clicked),
                    NULL);

  /* Store pointers to all widgets, for use by lookup_widget(). */
  GLADE_HOOKUP_OBJECT_NO_REF (window2, window2, "window2");
  GLADE_HOOKUP_OBJECT (window2, fixed9, "fixed9");
  GLADE_HOOKUP_OBJECT (window2, label42, "label42");
  GLADE_HOOKUP_OBJECT (window2, buttondaliaffiche, "buttondaliaffiche");
  GLADE_HOOKUP_OBJECT (window2, alignment7, "alignment7");
  GLADE_HOOKUP_OBJECT (window2, hbox7, "hbox7");
  GLADE_HOOKUP_OBJECT (window2, image7, "image7");
  GLADE_HOOKUP_OBJECT (window2, labeldaliseche, "labeldaliseche");
  GLADE_HOOKUP_OBJECT (window2, textviewAnseche, "textviewAnseche");

  return window2;
}

